twitter_username: pbloemesquire
title_image: "kai.cs.vu.nl/images/ceiling.jpg"
description: Knowledge and AI research group at Vrije Universiteit Amsterdam
plugins:
  - jekyll-redirect-from

markdown: kramdown

collections:
  news:
    date: true
    summary: true
    extra_content: true
    output: true


baseurl: /
