title_image: "kai.cs.vu.nl/images/ceiling.jpg"
description: Knowledge and AI research group at Vrije Universiteit Amsterdam
plugins:
  - jekyll-redirect-from

markdown: kramdown

collections:
  news:
    date: true
    summary: true
    extra_content: true
    output: true
  theses_dir:
    title: true
    description: true
    layout: default
    topic: true
    keywords: true
    supervisor: true
    contact: true
    degree: true
    description_link: true
    output: true

theses_keywords: >
    Knowledge Representation,
    Knowledge Graphs,
    Reasoning,
    Ontologies,
    Robotics,
    Logics,
    Knowledge Engineering,
    Ontology Engineering,
    LLM,
    Hybrid Intelligence,
    Wikipedia,
    Semantic Web,
    Python,
    Machine Learning,
    Logic-Based Argumentation,
    Java,
    Explainability,
    Description Logics,
    Change Management,

baseurl: /
