title_image: "kai.cs.vu.nl/images/ceiling.jpg"
description: Knowledge and AI research group at Vrije Universiteit Amsterdam
plugins:
  - jekyll-redirect-from

markdown: kramdown

collections:
  news:
    date: true
    summary: true
    extra_content: true
    output: true
  theses_dir:
    title: true
    description: true
    layout: default
    topic: true
    keywords: true
    supervisor: true
    contact: true
    degree: true
    description_link: true
    output: true

theses_keywords: >
    ML,
    LLM,
    Ontology engineering,
    KG embeddings,
    Knowledge representation,
    Description logic,
    User testing,
    Validity testing,
    Decision analysis

theses_topics: >
    Information Extraction,
    Ontology Evolution,
    Hybrid Intelligence,
    Argument and Rule Mining,
    Robotics and Knowledge Representation,
    Explanations and Narratives,
    Question Answering,
    Multi-lingual problems,
    Semantics of Deep Learning Methods,
    Systems of artificial intelligent agents,
    Explanations for Ontologies,
    Other Topics on Ontologies and Description Logics

baseurl: /
